### ISSUE TITLE
table's inner data edit UI is not so friendly that we have no choice but use the popup page to update the data one by one instead

### ISSUE THREAD

**Issue by singerila2008** [ant-ued/blog#7]
建议：直接在表格单元格中编辑数据显示的园框效果太差，以至于做的编辑功能都是以弹出修改页面的形式，操作不便，还请大神能够优化Table表格的编辑显示功能，可参考
![image](https://cloud.githubusercontent.com/assets/6194651/15110490/d7ae2fe8-1613-11e6-82b8-fdc9aed3cc0e.png)

**Comment by superRaytin** [comment]
Ant Design 问题请到这里 https://github.com/ant-design/ant-design/ 提问
